import Head from 'next/head'
import dynamic from 'next/dynamic'
import styled from "styled-components"
import { LoadingOutlined } from '@ant-design/icons'

export default function Chain() {
  
  const Spinner = ({ color }: { color: string }) => {
    return (
      <SpinContainer>
        <LoadingOutlined style={{ fontSize: '64px', color }} spin />
      </SpinContainer>
    )
  }
  const dynOptions = { loading: function spinner() { return ( <Spinner color={"black"} /> ) }, ssr: false };
  const DynChain = dynamic(() => import('./App'), dynOptions);

  return (
    <>
      <Head>
        <title>{`Figment Learn - Arweave Pathway`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynChain />
    </>
  )
}

const SpinContainer = styled.div`
  display: flex;
  min-height: 100vh;
  justify-content: center;
  align-items: center;
`;
